import = brings in code from another module or library
def = defines new function
return = sends a value back from a function
print() = displays output to the user
input() = gets input from the user 
if = starts a conditional statement
elif = else if, another condition in a conditional statement
else = the final condition in a conditional statement
while True: = starts an infinite loop
break = exits a loop
continue = skips to the next iteration of a loop
for = starts a loop that iterates over a sequence
in = used to check membership or to iterate over a sequence
list = a collection of items that is ordered and changeable
dict = a collection of key-value pairs
try = starts a block of code that will be tested for errors
except = handles the error if one occurs in the try block
with = used to wrap the execution of a block with methods defined by a context manager
open() = opens a file
read() = reads the contents of a file
write() = writes data to a file
append() = adds an item to the end of a list or file
strip() = removes whitespace from the beginning and end of a string
split() = divides a string into a list based on a delimiter
join() = combines a list of strings into a single string with a specified delimiter
len() = returns the length of a string, list, or other collection
range() = generates a sequence of numbers
